const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),Flow=require('../site/physical-quest-flow.js');
function fixture(){
  const flags={},root={SCENES:{},sceneState:{flags},gameState:{character:{inventory:[]}},PhysicalQuestFlow:Flow,document:{body:{classList:{contains:()=>true}}},addLog(){},grantXP(){},grantHolyPoints(){},grantHellPoints(){}};root.window=root;root.getFlag=k=>flags[k];root.setFlag=(k,v=true)=>flags[k]=v;
  const engine=root.__world3d={zone:{id:'vaelthar_city',interactables:[{id:'npc:captain_rhael'}]},physicalContext:null,hasPhysicalInteraction:id=>engine.physicalContext===id,physicalReach:()=>true,toast(){}};
  vm.runInNewContext(fs.readFileSync(require.resolve('../site/story-extra-children.js'),'utf8'),root);
  root.runScene=id=>{if(!Flow.requireScene(root,id))return false;return root.SCENES[id]();};
  return{root,flags,engine};
}
test('absent Rane leaves an actionable exhibition docket instead of blocking case access',()=>{
  for(const fate of ['dead','arrested','fled']){const {root,flags,engine}=fixture();Object.assign(flags,{ambassador_quest_started:true,ambassador_last_words_heard:true,npc_fate_undersecretary_rane:fate});engine.zone={id:'ostrene_legation',interactables:[{id:'ostrene_chancery_case'}]};engine.physicalContext='ostrene_chancery_case';const scene=root.runScene('ambassador_strongbox');assert.match(scene.narration,/courier docket/);assert.equal(scene.options.length,1);scene.options[0].action();assert.equal(flags.rane_refused_once,true);assert.equal(root.sceneState.physicalSceneRequests.ostrene_wool_exhibition,'ambassador_wool_exhibition');}
});
test('absent-clerk collation preserves the clue and reward without inventing her help',()=>{
  const {root,flags,engine}=fixture();Object.assign(flags,{ambassador_quest_started:true,rane_refused_once:true,ostrene_exhibition_attended:true,npc_dead_undersecretary_rane:true});engine.zone={id:'vaelthar_city',interactables:[{id:'ostrene_wool_exhibition'}]};engine.physicalContext='ostrene_wool_exhibition';let xp=0;root.grantXP=n=>xp+=n;const scene=root.runScene('ambassador_seven_clauses');assert.doesNotMatch(scene.options[1].label,/Rane/);scene.options[1].action();scene.options[1].action();assert.equal(xp,80);assert.equal(flags.clue_seventh_clause_exists,true);assert.equal(flags.rane_collated_it,undefined);assert.equal(flags.ambassador_seizure_pending,true);
});
test('stale Rane-dependent callbacks refresh when she becomes absent',()=>{
  const {root,flags,engine}=fixture();Object.assign(flags,{ambassador_quest_started:true,ambassador_last_words_heard:true});engine.zone={id:'ostrene_legation',interactables:[{id:'ostrene_chancery_case'}]};engine.physicalContext='ostrene_chancery_case';const scene=root.runScene('ambassador_seven_clauses');flags.npc_dead_undersecretary_rane=true;scene.options[1].action();assert.equal(flags.rane_collated_it,undefined);assert.equal(flags.clue_seventh_clause_exists,undefined);assert.equal(flags.ambassador_seizure_pending,undefined);
});
test('absent Rane is not narrated at Halven bedside or the kept-exemplar handoff',()=>{
  const {root,flags,engine}=fixture();Object.assign(flags,{ambassador_quest_started:true,npc_dead_undersecretary_rane:true});engine.zone={id:'ostrene_legation',interactables:[{id:'npc:oret_halven'}]};engine.physicalContext='npc:oret_halven';const bedside=root.runScene('ambassador_bedside');assert.doesNotMatch(bedside.narration,/Rane/);bedside.options[3].action();assert.equal(flags.rane_trusts_you,undefined);const words=root.runScene('ambassador_last_words');assert.equal(words.options.length,1);assert.doesNotMatch(words.narration,/Rane/);flags.ambassador_seizure_pending=true;assert.doesNotMatch(root.SCENES.ambassador_exemplar_kept().narration,/Rane/);
});
test('outdoor exemplar outcomes retain wool-gate setting without a bedside scene',()=>{
  for(const kept of [false,true]){const {root,flags}=fixture();Object.assign(flags,{ambassador_quest_started:true,ambassador_seizure_pending:true,ambassador_seizure_at_wool:true});const scene=root.SCENES[kept?'ambassador_exemplar_kept':'ambassador_exemplar_surrendered']();assert.match(scene.location,/Wool Gate/);assert.doesNotMatch(scene.narration,/in this room|looks at the bed|Rane puts/);}
});
test('receipt success and failure show a visible follow-up without opening remote city actions',()=>{
  for(const success of [false,true])for(const wool of [false,true]){const {root,flags}=fixture();Object.assign(flags,{chancery_took_exemplar:true,ambassador_seizure_at_wool:wool});let shown;root.showScene=scene=>shown=scene;root.runScene=()=>assert.fail('remote scene opened');const receipt=root.SCENES.ambassador_exemplar_surrendered().options[0];receipt[success?'onSuccess':'onFail']();assert.ok(shown.narration);assert.match(shown.location,wool?/Wool Gate/:/Legation/);assert.equal(!!flags.saw_standing_instruction_date,success);shown.options[0].action();}
});
test('stale receipt callbacks cannot apply a guest or conflicting outcome effect',()=>{
  for(const guest of [false,true]){const {root,flags}=fixture();flags.chancery_took_exemplar=true;const receipt=root.SCENES.ambassador_exemplar_surrendered().options[0];if(guest)root.mp={sessionCode:'party',isHost:false};else flags.has_ostrene_exemplar=true;root.showScene=()=>assert.fail('invalid receipt shown');receipt.onSuccess();assert.equal(flags.saw_standing_instruction_date,undefined);}
});
test('ambassador departures end dialogue without remotely opening city scenes',()=>{
  for(const kept of [false,true])for(const city of [false,true]){
    const {root,flags,engine}=fixture();Object.assign(flags,{ambassador_quest_started:true,ambassador_seizure_pending:true});engine.zone.id=city?'vaelthar_city':'ostrene_legation';
    const scene=root.SCENES[kept?'ambassador_exemplar_kept':'ambassador_exemplar_surrendered']();let message='';engine.toast=text=>message=text;root.runScene=()=>assert.fail('remote city scene opened');scene.options.find(o=>o.label.startsWith('End the conversation')).action();assert.match(message,city?/Continue exploring/:/legation door/);assert.equal(engine.zone.id,city?'vaelthar_city':'ostrene_legation');
  }
});
test('ambassador departure preserves the non-3D chronicle fallback',()=>{const {root,flags}=fixture();flags.chancery_took_exemplar=true;root.document.body.classList.contains=()=>false;let next;root.runScene=id=>next=id;root.SCENES.ambassador_exemplar_surrendered().options.find(o=>o.label.startsWith('End the conversation')).action();assert.equal(next,'vaelthar_main');});
test('exemplar resolutions are exclusive and reward only once, including after reload',()=>{
  for(const kept of [false,true]){
    const {root,flags}=fixture();Object.assign(flags,{ambassador_quest_started:true,ambassador_seizure_pending:true});
    let xp=0;root.grantXP=n=>xp+=n;
    const scene=kept?'ambassador_exemplar_kept':'ambassador_exemplar_surrendered',other=kept?'ambassador_exemplar_surrendered':'ambassador_exemplar_kept';
    assert.ok(root.SCENES[scene]());assert.ok(root.SCENES[scene]());assert.equal(root.SCENES[other](),null);
    assert.equal(xp,kept?150:120);assert.equal(flags.ambassador_seizure_pending,false);
    const reload=fixture();Object.assign(reload.flags,JSON.parse(JSON.stringify(flags)));reload.root.grantXP=()=>assert.fail('reward repeated after reload');
    assert.ok(reload.root.SCENES[scene]());assert.equal(reload.root.gameState.character.inventory.length,0,'reopening does not recreate a sold or transferred item');
  }
});
test('legacy exemplar rewards are not repaid and guests or unstarted quests cannot resolve',()=>{
  for(const flag of ['has_ostrene_exemplar','chancery_took_exemplar']){
    const {root,flags}=fixture();flags[flag]=true;root.grantXP=()=>assert.fail('legacy reward repeated');
    assert.ok(root.SCENES[flag==='has_ostrene_exemplar'?'ambassador_exemplar_kept':'ambassador_exemplar_surrendered']());
    assert.equal(flags.ambassador_reward_exemplar,true);
  }
  for(const guest of [false,true]){const {root,flags}=fixture();if(guest){Object.assign(flags,{ambassador_quest_started:true,ambassador_seizure_pending:true});root.mp={sessionCode:'party',isHost:false};}assert.equal(root.SCENES.ambassador_exemplar_kept(),null);assert.equal(root.SCENES.ambassador_exemplar_surrendered(),null);assert.equal(flags.ambassador_reward_exemplar,undefined);}
});
test('page-one choices cannot stack collation rewards or restart after resolution',()=>{
  for(const legacy of [false,true]){
    const {root,flags,engine}=fixture();Object.assign(flags,{ambassador_quest_started:true,ambassador_last_words_heard:true,aldran_intel:true,clue_seventh_clause_exists:legacy});
    engine.zone={id:'ostrene_legation',interactables:[{id:'ostrene_chancery_case'}]};engine.physicalContext='ostrene_chancery_case';let xp=0;root.grantXP=n=>xp+=n;
    const scene=root.runScene('ambassador_seven_clauses');scene.options[0].onSuccess();scene.options[1].action();scene.options[3].action();
    assert.equal(xp,legacy?0:120);assert.equal(root.SCENES.ambassador_seven_clauses(),null);
    root.SCENES.ambassador_exemplar_surrendered();scene.options[0].onSuccess();assert.equal(xp,(legacy?0:120)+120);assert.equal(flags.ambassador_seizure_pending,false);
  }
});
test('bedside patience and case theft grant alignment once per choice',()=>{
  const {root,flags,engine}=fixture();flags.ambassador_quest_started=true;engine.zone={id:'ostrene_legation',interactables:[{id:'npc:oret_halven'},{id:'ostrene_chancery_case'}]};engine.physicalContext='npc:oret_halven';let holy=0,hell=0;root.grantHolyPoints=n=>holy+=n;root.grantHellPoints=n=>hell+=n;
  const bedside=root.runScene('ambassador_bedside');const sit=bedside.options.find(o=>o.label.startsWith('Sit down'));sit.action();sit.action();assert.equal(holy,5);
  const words=root.runScene('ambassador_last_words');const wait=words.options.find(o=>o.label.includes('Rane'));assert.ok(wait);wait.action();wait.action();assert.equal(holy,8);
  engine.physicalContext='ostrene_chancery_case';const box=root.runScene('ambassador_strongbox');const steal=box.options.find(o=>o.roll?.stat==='DEX');steal.onSuccess();steal.onSuccess();assert.equal(hell,4);
});
test('the exemplar handoff queues Rhael instead of narrating a remote conversation',()=>{
  const {root,flags,engine}=fixture();Object.assign(flags,{ambassador_quest_started:true,ambassador_seizure_pending:true});const scene=root.SCENES.ambassador_exemplar_kept();scene.options[0].action();
  assert.equal(flags.rhael_shown_exemplar,undefined);assert.equal(root.sceneState.physicalSceneRequests['npc:captain_rhael'],'ambassador_rhael_report');
  assert.equal(Flow.nextScene('npc:captain_rhael',root.sceneState,{activeQuests:[]}), 'ambassador_rhael_report');
  engine.physicalContext='npc:captain_rhael';const report=root.runScene('ambassador_rhael_report');assert.match(report.narration,/printing decision/);assert.equal(flags.rhael_shown_exemplar,true);
  assert.equal(root.sceneState.physicalSceneRequests['npc:captain_rhael'],undefined);
});
test('Rhael report rejects missing evidence, surrender, absence and lost reach',()=>{
  for(const condition of ['missing','surrendered','absent','remote']){const {root,flags,engine}=fixture();flags.has_ostrene_exemplar=condition!=='missing';flags.chancery_took_exemplar=condition==='surrendered';engine.physicalContext='npc:captain_rhael';if(condition==='remote')engine.physicalReach=()=>false;if(condition==='absent')engine.zone.interactables=[];assert.equal(root.SCENES.ambassador_rhael_report(),null);assert.equal(flags.rhael_shown_exemplar,undefined);}
});
test('pending Rhael handoff survives strict saved-request restoration',()=>{const pending={'npc:captain_rhael':'ambassador_rhael_report'};assert.deepEqual(Flow.restoreRequests(JSON.parse(JSON.stringify(pending))),pending);});
test('Halven must be visited before his confession and the case requires a separate interaction',()=>{const {root,flags,engine}=fixture();flags.ambassador_quest_started=true;assert.equal(root.runScene('ambassador_bedside'),false);assert.equal(flags.clue_covenant_expires,undefined);engine.zone={id:'ostrene_legation',interactables:[{id:'npc:oret_halven'},{id:'ostrene_chancery_case'}]};engine.physicalContext='npc:oret_halven';assert.ok(root.runScene('ambassador_bedside'));assert.equal(flags.clue_covenant_expires,true);let xp=0;root.grantXP=n=>xp+=n;const last=root.runScene('ambassador_last_words');root.runScene('ambassador_last_words');assert.equal(xp,80);last.options[0].action();assert.equal(root.sceneState.physicalSceneRequests.ostrene_chancery_case,'ambassador_strongbox');engine.physicalContext='ostrene_chancery_case';assert.ok(root.runScene('ambassador_strongbox'));});
test('case access cannot precede Halven and stale bedside callbacks cannot advance from elsewhere',()=>{const {root,flags,engine}=fixture();flags.ambassador_quest_started=true;engine.zone={id:'ostrene_legation',interactables:[{id:'npc:oret_halven'},{id:'ostrene_chancery_case'}]};engine.physicalContext='ostrene_chancery_case';assert.equal(root.SCENES.ambassador_strongbox(),null);engine.physicalContext='npc:oret_halven';const scene=root.runScene('ambassador_bedside');engine.physicalContext=null;scene.options[1].action();assert.equal(flags.ambassador_last_words_heard,undefined);});
test('legation handoffs survive request restoration',()=>{const requests={'npc:oret_halven':'ambassador_bedside',ostrene_chancery_case:'ambassador_strongbox'};assert.deepEqual(Flow.restoreRequests(JSON.parse(JSON.stringify(requests))),requests);});
test('Rane refusal queues a physical wool-gate exhibition instead of opening page one remotely',()=>{const {root,flags,engine}=fixture();Object.assign(flags,{ambassador_quest_started:true,ambassador_last_words_heard:true});engine.zone={id:'ostrene_legation',interactables:[{id:'ostrene_chancery_case'}]};engine.physicalContext='ostrene_chancery_case';const refusal=root.runScene('ambassador_rane_refuses');refusal.options[0].action();assert.equal(flags.ostrene_exhibition_attended,undefined);assert.equal(root.sceneState.physicalSceneRequests.ostrene_wool_exhibition,'ambassador_wool_exhibition');root.runScene('ambassador_seven_clauses');assert.equal(flags.clue_seventh_clause_exists,undefined);});
test('exhibition waiting requires current physical context and safely reaches the next fifth bell',()=>{for(const hour of [10,17,20]){const {root,flags,engine}=fixture();Object.assign(flags,{ambassador_quest_started:true,rane_refused_once:true});engine.zone={id:'vaelthar_city',interactables:[{id:'ostrene_wool_exhibition'}]};engine.physicalContext='ostrene_wool_exhibition';root.worldClock={hour};let waited=0;root.advanceTime=n=>{waited+=n;root.worldClock.hour=(hour+n)%24;};const scene=root.runScene('ambassador_wool_exhibition');engine.physicalContext=null;scene.options[0].action();assert.equal(waited,0);assert.equal(flags.ostrene_exhibition_attended,undefined);engine.physicalContext='ostrene_wool_exhibition';scene.options[0].action();assert.equal(waited,(17-hour+24)%24);assert.equal(flags.ostrene_exhibition_attended,true);}});
test('wool exhibition request survives reload and cannot be opened before refusal',()=>{const {root}=fixture();assert.equal(root.SCENES.ambassador_wool_exhibition(),null);const requests={ostrene_wool_exhibition:'ambassador_wool_exhibition'};assert.deepEqual(Flow.restoreRequests(JSON.parse(JSON.stringify(requests))),requests);});
test('reading either counterpart queues the Brask actor at the correct location',()=>{for(const wool of [false,true]){const {root,flags,engine}=fixture();Object.assign(flags,{ambassador_quest_started:true,ambassador_last_words_heard:true,rane_refused_once:wool,ostrene_exhibition_attended:wool});const brask=wool?'npc:wool_gate_brask':'npc:chancery_brask',caseId=wool?'ostrene_wool_exhibition':'ostrene_chancery_case';engine.zone={id:wool?'vaelthar_city':'ostrene_legation',interactables:[{id:caseId},{id:brask}]};engine.physicalContext=caseId;const reading=root.runScene('ambassador_seven_clauses');reading.options.find(o=>o.label.startsWith('Let Rane')).action();assert.equal(flags.ambassador_seizure_pending,true);assert.equal(root.sceneState.physicalSceneRequests[brask],'ambassador_chancery_seizure');let combats=0;root.startCombat=()=>combats++;engine.physicalContext=brask;const encounter=root.runScene('ambassador_chancery_seizure');assert.ok(encounter);engine.physicalContext=null;encounter.options.find(o=>o.type==='combat').action();assert.equal(combats,0);engine.physicalContext=brask;encounter.options.find(o=>o.type==='combat').action();assert.equal(combats,1);}});
test('Brask staging is exclusive and ends on resolution or absence',()=>{for(const wool of [false,true]){const state={flags:{ambassador_seizure_pending:true,ambassador_seizure_at_wool:wool}},id=wool?'wool_gate_brask':'chancery_brask',location=wool?'vaelthar_city':'ostrene_legation';assert.equal(Flow.npcStage(id,location,state).active,true);assert.equal(Flow.npcStage(wool?'chancery_brask':'wool_gate_brask',wool?'ostrene_legation':'vaelthar_city',state).active,false);for(const flag of ['has_ostrene_exemplar','chancery_took_exemplar','npc_dead_chancery_brask']){state.flags[flag]=true;assert.equal(Flow.npcStage(id,location,state).active,false);delete state.flags[flag];}for(const fate of ['dead','arrested','fled']){state.flags.npc_fate_chancery_brask=fate;assert.equal(Flow.npcStage(id,location,state).active,false);}}});
test('both Brask handoffs survive strict saved-request restoration',()=>{for(const id of ['npc:chancery_brask','npc:wool_gate_brask']){const requests={[id]:'ambassador_chancery_seizure'};assert.deepEqual(Flow.restoreRequests(JSON.parse(JSON.stringify(requests))),requests);}});
test('Rhael retains his normal conversation when no report is pending',async()=>{const {refreshPhysicalQuestTargets}=await import('../site/world3d/physical-quest-targets.mjs');const original=global.window;try{const record={id:'npc:captain_rhael',actions:[],onInteract:()=>{}};global.window={PhysicalQuestFlow:Flow,sceneState:{flags:{},physicalSceneRequests:{'npc:captain_rhael':'ambassador_rhael_report'}},gameState:{}};const engine={zone:{id:'vaelthar_city',interactables:[record]}};refreshPhysicalQuestTargets(engine);assert.equal(record.actions.length,1);global.window.sceneState.physicalSceneRequests={};refreshPhysicalQuestTargets(engine);assert.equal(record.actions.length,0);assert.equal(typeof record.onInteract,'function');}finally{global.window=original;}});
