const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),Flow=require('../site/physical-quest-flow.js');
function fixture(){
  const flags={},root={SCENES:{},sceneState:{flags},gameState:{character:{inventory:[]}},PhysicalQuestFlow:Flow,document:{body:{classList:{contains:()=>true}}},addLog(){},grantXP(){},grantHolyPoints(){},grantHellPoints(){}};root.window=root;root.getFlag=k=>flags[k];root.setFlag=(k,v=true)=>flags[k]=v;
  const engine=root.__world3d={zone:{id:'vaelthar_city',interactables:[{id:'npc:captain_rhael'}]},physicalContext:null,hasPhysicalInteraction:id=>engine.physicalContext===id,physicalReach:()=>true,toast(){}};
  vm.runInNewContext(fs.readFileSync(require.resolve('../site/story-extra-children.js'),'utf8'),root);
  root.runScene=id=>{if(!Flow.requireScene(root,id))return false;return root.SCENES[id]();};
  return{root,flags,engine};
}
test('the exemplar handoff queues Rhael instead of narrating a remote conversation',()=>{
  const {root,flags,engine}=fixture();const scene=root.SCENES.ambassador_exemplar_kept();scene.options[0].action();
  assert.equal(flags.rhael_shown_exemplar,undefined);assert.equal(root.sceneState.physicalSceneRequests['npc:captain_rhael'],'ambassador_rhael_report');
  assert.equal(Flow.nextScene('npc:captain_rhael',root.sceneState,{activeQuests:[]}), 'ambassador_rhael_report');
  engine.physicalContext='npc:captain_rhael';const report=root.runScene('ambassador_rhael_report');assert.match(report.narration,/printing decision/);assert.equal(flags.rhael_shown_exemplar,true);
  assert.equal(root.sceneState.physicalSceneRequests['npc:captain_rhael'],undefined);
});
test('Rhael report rejects missing evidence, surrender, absence and lost reach',()=>{
  for(const condition of ['missing','surrendered','absent','remote']){const {root,flags,engine}=fixture();flags.has_ostrene_exemplar=condition!=='missing';flags.chancery_took_exemplar=condition==='surrendered';engine.physicalContext='npc:captain_rhael';if(condition==='remote')engine.physicalReach=()=>false;if(condition==='absent')engine.zone.interactables=[];assert.equal(root.SCENES.ambassador_rhael_report(),null);assert.equal(flags.rhael_shown_exemplar,undefined);}
});
test('pending Rhael handoff survives strict saved-request restoration',()=>{const pending={'npc:captain_rhael':'ambassador_rhael_report'};assert.deepEqual(Flow.restoreRequests(JSON.parse(JSON.stringify(pending))),pending);});
test('Halven must be visited before his confession and the case requires a separate interaction',()=>{const {root,flags,engine}=fixture();flags.ambassador_quest_started=true;assert.equal(root.runScene('ambassador_bedside'),false);assert.equal(flags.clue_covenant_expires,undefined);engine.zone={id:'ostrene_legation',interactables:[{id:'npc:oret_halven'},{id:'ostrene_chancery_case'}]};engine.physicalContext='npc:oret_halven';assert.ok(root.runScene('ambassador_bedside'));assert.equal(flags.clue_covenant_expires,true);let xp=0;root.grantXP=n=>xp+=n;const last=root.runScene('ambassador_last_words');root.runScene('ambassador_last_words');assert.equal(xp,80);last.options[0].action();assert.equal(root.sceneState.physicalSceneRequests.ostrene_chancery_case,'ambassador_strongbox');engine.physicalContext='ostrene_chancery_case';assert.ok(root.runScene('ambassador_strongbox'));});
test('case access cannot precede Halven and stale bedside callbacks cannot advance from elsewhere',()=>{const {root,flags,engine}=fixture();flags.ambassador_quest_started=true;engine.zone={id:'ostrene_legation',interactables:[{id:'npc:oret_halven'},{id:'ostrene_chancery_case'}]};engine.physicalContext='ostrene_chancery_case';assert.equal(root.SCENES.ambassador_strongbox(),null);engine.physicalContext='npc:oret_halven';const scene=root.runScene('ambassador_bedside');engine.physicalContext=null;scene.options[1].action();assert.equal(flags.ambassador_last_words_heard,undefined);});
test('legation handoffs survive request restoration',()=>{const requests={'npc:oret_halven':'ambassador_bedside',ostrene_chancery_case:'ambassador_strongbox'};assert.deepEqual(Flow.restoreRequests(JSON.parse(JSON.stringify(requests))),requests);});
test('Rhael retains his normal conversation when no report is pending',async()=>{const {refreshPhysicalQuestTargets}=await import('../site/world3d/physical-quest-targets.mjs');const original=global.window;try{const record={id:'npc:captain_rhael',actions:[],onInteract:()=>{}};global.window={PhysicalQuestFlow:Flow,sceneState:{flags:{},physicalSceneRequests:{'npc:captain_rhael':'ambassador_rhael_report'}},gameState:{}};const engine={zone:{id:'vaelthar_city',interactables:[record]}};refreshPhysicalQuestTargets(engine);assert.equal(record.actions.length,1);global.window.sceneState.physicalSceneRequests={};refreshPhysicalQuestTargets(engine);assert.equal(record.actions.length,0);assert.equal(typeof record.onInteract,'function');}finally{global.window=original;}});
