const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),Flow=require('../site/physical-quest-flow.js');
function fixture(){
 const root={SCENES:{},sceneState:{flags:{}},gameState:{activeQuests:[{id:'c1q20'}]},document:{body:{classList:{contains:()=>true}}},PhysicalQuestFlow:Flow,xp:0,holy:0,addLog(){},combats:0};root.window=root;root.getFlag=k=>root.sceneState.flags[k];root.setFlag=(k,v=true)=>root.sceneState.flags[k]=v;root.grantXP=n=>root.xp+=n;root.grantHolyPoints=n=>root.holy+=n;root.startCombat=()=>root.combats++;
 const engine=root.__world3d={zone:{id:'tower_ash',interactables:Object.keys(Flow.TARGETS).map(id=>({id}))},physicalContext:null,hasPhysicalInteraction:id=>engine.physicalContext===id,physicalReach:()=>true,toast(){}};let scene;
 root.runScene=id=>{scene=null;if(!Flow.requireScene(root,id))return false;scene=root.SCENES[id]();return !!scene;};vm.runInNewContext(fs.readFileSync(require.resolve('../site/story-extra-finale.js'),'utf8'),root);
 return{root,engine,flags:root.sceneState.flags,scene:()=>scene,at(id,scene){engine.zone.id=Flow.TARGETS[id].location;engine.physicalContext=id;return root.runScene(scene||Flow.TARGETS[id].scene);}};
}
test('Tower arrival cannot grant entry or confrontation without an explicit interaction',()=>{const f=fixture();assert.equal(f.root.runScene('tower_ash_approach'),false);assert.equal(f.flags.tower_ash_entered,undefined);f.at('tower_sealed_door');assert.equal(f.flags.tower_ash_entered,true);assert.equal(f.flags.faced_the_shattered_god,undefined);});
test('every door outcome queues the interior confrontation instead of starting it outside',()=>{for(const choice of ['knock','success','failure','name']){const f=fixture();f.flags.knows_the_name_early=true;f.at('tower_sealed_door');const opts=f.scene().options;if(choice==='knock')opts.find(o=>o.label.startsWith('Knock')).action();else if(choice==='name')opts.find(o=>o.label.includes('Selvane')).action();else opts[0][choice==='success'?'onSuccess':'onFail']();assert.equal(f.flags.tower_door_answered,true);assert.equal(f.flags.faced_the_shattered_god,undefined);assert.equal(f.root.sceneState.physicalSceneRequests.tower_last_step,'tower_thirty_seventh_step');f.at('tower_last_step');assert.equal(f.flags.faced_the_shattered_god,true);}});
test('interior bypass redirects to door; existing confronted saves remain compatible',()=>{const f=fixture();assert.equal(f.at('tower_last_step'),false);assert.equal(f.flags.faced_the_shattered_god,undefined);assert.equal(f.root.sceneState.physicalSceneRequests.tower_sealed_door,'tower_ash_approach');f.flags.faced_the_shattered_god=true;assert.equal(f.at('tower_last_step'),true);});
test('door rewards are once-only and stale checks revalidate range',()=>{const f=fixture();f.at('tower_sealed_door');const success=f.scene().options[0].onSuccess;f.engine.physicalReach=()=>false;success();assert.equal(f.root.xp,0);f.engine.physicalReach=()=>true;success();success();assert.equal(f.root.xp,90);});
test('confrontation conversation rewards do not repeat and stale attacks cannot start',()=>{const f=fixture();f.flags.tower_door_answered=true;f.at('tower_last_step','tower_name_without_name');f.at('tower_last_step','tower_name_without_name');assert.equal(f.root.holy,5);const ask=f.scene().options.find(o=>o.label.startsWith('Ask it'));ask.action();ask.action();assert.equal(f.root.xp,80);f.at('tower_last_step');const fight=f.scene().options.find(o=>o.type==='combat');f.engine.zone.id='tower_ash';fight.action();assert.equal(f.root.combats,0);});
test('turning away from the Tower in 3D does not teleport to another region',()=>{const f=fixture();f.root.goTo=()=>assert.fail('remote travel');f.at('tower_sealed_door');f.scene().options.at(-1).action();assert.equal(f.engine.zone.id,'tower_ash');});
