const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),Flow=require('../site/physical-quest-flow.js');
test('combat HUD does not trap the fixed initiative strip inside its transformed ability bar',()=>{const css=fs.readFileSync(require.resolve('../site/world3d.css'),'utf8');assert.match(css,/\.world3d-combat-hud\{right:auto;left:max\(19px,calc\(\(100% - 920px\)\/2\)\);[^}]*transform:none/);});
test('Tower progress keeps the exterior unlocked for returning interior saves',()=>{const source=fs.readFileSync(require.resolve('../site/map.js'),'utf8'),start=source.indexOf('const PROGRESS_UNLOCKS ='),end=source.indexOf('window.unlockLocationsByProgress = unlockLocationsByProgress;')+'window.unlockLocationsByProgress = unlockLocationsByProgress;'.length;for(const flag of [null,'tower_opened','unlocked_tower_ash','tower_door_answered','faced_the_shattered_god']){const locations={tower_ash:{locked:true}},window={sceneState:{flags:flag?{[flag]:true}:{}}};vm.runInNewContext(source.slice(start,end),{window,WORLD_LOCATIONS:locations});window.unlockLocationsByProgress();assert.equal(locations.tower_ash.locked,!flag);}});
function fixture(){
 const root={SCENES:{},sceneState:{flags:{}},gameState:{activeQuests:[{id:'c1q20'}]},document:{body:{classList:{contains:()=>true}}},PhysicalQuestFlow:Flow,xp:0,holy:0,addLog(){},combats:0};root.window=root;root.getFlag=k=>root.sceneState.flags[k];root.setFlag=(k,v=true)=>root.sceneState.flags[k]=v;root.grantXP=n=>root.xp+=n;root.grantHolyPoints=n=>root.holy+=n;root.startCombat=()=>root.combats++;
 const engine=root.__world3d={zone:{id:'tower_ash',interactables:Object.keys(Flow.TARGETS).map(id=>({id}))},physicalContext:null,hasPhysicalInteraction:id=>engine.physicalContext===id,physicalReach:()=>true,toast(){}};let scene;
 root.runScene=id=>{scene=null;if(!Flow.requireScene(root,id))return false;scene=root.SCENES[id]();return !!scene;};vm.runInNewContext(fs.readFileSync(require.resolve('../site/story-extra-finale.js'),'utf8'),root);
 return{root,engine,flags:root.sceneState.flags,scene:()=>scene,at(id,scene){engine.zone.id=Flow.TARGETS[id].location;engine.physicalContext=id;return root.runScene(scene||Flow.TARGETS[id].scene);}};
}
test('Tower arrival cannot grant entry or confrontation without an explicit interaction',()=>{const f=fixture();assert.equal(f.root.runScene('tower_ash_approach'),false);assert.equal(f.flags.tower_ash_entered,undefined);f.at('tower_sealed_door');assert.equal(f.flags.tower_ash_entered,true);assert.equal(f.flags.faced_the_shattered_god,undefined);});
test('every door outcome queues the interior confrontation instead of starting it outside',()=>{for(const choice of ['knock','success','failure','name']){const f=fixture();f.flags.knows_the_name_early=true;f.at('tower_sealed_door');const opts=f.scene().options;if(choice==='knock')opts.find(o=>o.label.startsWith('Knock')).action();else if(choice==='name')opts.find(o=>o.label.includes('Selvane')).action();else opts[0][choice==='success'?'onSuccess':'onFail']();assert.equal(f.flags.tower_door_answered,true);assert.equal(f.flags.faced_the_shattered_god,undefined);assert.equal(f.root.sceneState.physicalSceneRequests.tower_last_step,'tower_thirty_seventh_step');f.at('tower_last_step');assert.equal(f.flags.faced_the_shattered_god,true);}});
test('interior bypass redirects to door; existing confronted saves remain compatible',()=>{const f=fixture();assert.equal(f.at('tower_last_step'),false);assert.equal(f.flags.faced_the_shattered_god,undefined);assert.equal(f.root.sceneState.physicalSceneRequests.tower_sealed_door,'tower_ash_approach');f.flags.faced_the_shattered_god=true;assert.equal(f.at('tower_last_step'),true);});
test('door rewards are once-only and stale checks revalidate range',()=>{const f=fixture();f.at('tower_sealed_door');const success=f.scene().options[0].onSuccess;f.engine.physicalReach=()=>false;success();assert.equal(f.root.xp,0);f.engine.physicalReach=()=>true;success();success();assert.equal(f.root.xp,90);});
test('confrontation conversation rewards do not repeat and stale attacks cannot start',()=>{const f=fixture();f.flags.tower_door_answered=true;f.at('tower_last_step','tower_name_without_name');f.at('tower_last_step','tower_name_without_name');assert.equal(f.root.holy,5);const ask=f.scene().options.find(o=>o.label.startsWith('Ask it'));ask.action();ask.action();assert.equal(f.root.xp,80);f.at('tower_last_step');const fight=f.scene().options.find(o=>o.type==='combat');f.engine.zone.id='tower_ash';fight.action();assert.equal(f.root.combats,0);});
test('turning away from the Tower in 3D does not teleport to another region',()=>{const f=fixture();f.root.goTo=()=>assert.fail('remote travel');f.at('tower_sealed_door');f.scene().options.at(-1).action();assert.equal(f.engine.zone.id,'tower_ash');});
function finale(ending){const f=fixture();f.root.grantHellPoints=()=>{};f.root.availableEndings=()=>({uprising:true,restoration:true,devour:true});Object.assign(f.flags,{faced_the_shattered_god:true,tower_door_answered:true,npc_dead_shattered_god:true,spoke_selvane:true,clue_old_benediction_six_lines:true,clue_eron_inscription:true,officer_player:true,player_tried_saying:true});f.engine.zone.id='tower_antechamber';f.engine.physicalContext='tower_last_step';f.open=()=>f.root.runScene('tower_ending_'+ending);return f;}
test('Cael recruitment requires visiting the monastery, then his Tower actor, then the stone',()=>{const f=finale('charter');delete f.flags.officer_player;f.flags.met_cael_sayer=true;f.at('tower_last_step','tower_charter_officer');f.scene().options.find(o=>o.label.startsWith('Brother Cael')).action();assert.equal(f.flags.tower_cael_invited,undefined);assert.equal(Flow.nextScene('npc:brother_cael',f.root.sceneState,f.root.gameState),'tower_invite_cael');f.at('npc:brother_cael','tower_invite_cael');f.scene().options[0].action();assert.equal(f.flags.tower_cael_invited,true);assert.equal(f.flags.officer_cael,undefined);f.at('npc:tower_cael');f.scene().options[0].action();assert.equal(f.flags.officer_cael,true);assert.equal(f.flags.chapter1_complete,undefined);assert.equal(f.root.sceneState.physicalSceneRequests.tower_last_step,'tower_charter_seal');f.at('tower_last_step','tower_charter_seal');f.scene().options[0].action();assert.equal(f.flags.chapter1_ending_charter,true);});
test('Theones must be recruited at reception and his failed attempt rewards once at the Tower',()=>{const f=finale('charter');f.flags.met_theones=true;f.flags.theones_broke=true;f.at('tower_last_step','tower_charter_officer');f.scene().options.find(o=>o.label.startsWith('Head Archivist')).action();assert.equal(f.flags.theones_tried,undefined);f.at('npc:head_archivist_theones','tower_invite_theones');f.scene().options[0].action();assert.equal(f.flags.tower_theones_invited,true);f.at('npc:tower_theones');const attempt=f.scene().options[0].action;attempt();attempt();assert.equal(f.root.xp,120);assert.equal(f.flags.chapter1_complete,undefined);});
test('recruited officers stage only at the Tower and leave it after the finale',()=>{for(const [id,base,home]of [['tower_cael','brother_cael','monastery_aldric'],['tower_theones','head_archivist_theones','church_archive']]){const state={flags:{met_cael_sayer:true,met_theones:true}};assert.equal(Flow.npcStage(id,'tower_antechamber',state).active,false);state.flags[id+'_invited']=true;assert.equal(Flow.npcStage(id,'tower_antechamber',state).active,true);assert.equal(Flow.npcStage(base,home,state).active,false);for(const fate of ['dead','arrested','fled']){state.flags['npc_fate_'+base]=fate;assert.equal(Flow.npcStage(id,'tower_antechamber',state).active,false);}delete state.flags['npc_fate_'+base];state.flags.chapter1_complete=true;assert.equal(Flow.npcStage(id,'tower_antechamber',state).active,false);}});
test('stale officer consent rechecks reach and absence',()=>{const f=finale('charter');f.flags.met_cael_sayer=true;f.flags.tower_cael_invited=true;f.at('npc:tower_cael');const consent=f.scene().options[0].action;f.engine.physicalReach=()=>false;consent();assert.equal(f.flags.officer_cael,undefined);f.engine.physicalReach=()=>true;f.flags.npc_dead_brother_cael=true;consent();assert.equal(f.flags.officer_cael,undefined);});
test('officer pending requests survive strict restoration and belong to quest twenty',()=>{const requests={'npc:brother_cael':'tower_invite_cael','npc:head_archivist_theones':'tower_invite_theones','npc:tower_cael':'tower_cael_warrant','npc:tower_theones':'tower_theones_attempt',tower_last_step:'tower_charter_seal'};assert.deepEqual(Flow.restoreRequests(JSON.parse(JSON.stringify(requests))),requests);assert.ok(Flow.TARGETS['npc:brother_cael'].quests.includes('c1q20'));assert.ok(Flow.TARGETS['npc:head_archivist_theones'].quests.includes('c1q20'));});
test('all six earned endings complete once and reject every conflicting ending',()=>{for(const ending of ['sword','charter','third_day','uprising','restoration','devour']){const f=finale(ending);assert.equal(f.open(),true,ending);assert.equal(f.flags.chapter1_complete,true);const xp=f.root.xp,holy=f.root.holy;f.open();assert.equal(f.root.xp,xp);assert.equal(f.root.holy,holy);for(const other of ['sword','charter','third_day','uprising','restoration','devour'])if(other!==ending)assert.equal(f.root.runScene('tower_ending_'+other),false);assert.equal(f.root.xp,xp);}});
test('sword requires recorded boss defeat and accepts a postcombat cleared context',()=>{const f=finale('sword');delete f.flags.npc_dead_shattered_god;assert.equal(f.open(),false);assert.equal(f.root.xp,0);f.flags.npc_dead_shattered_god=true;f.engine.physicalContext=null;assert.equal(f.open(),true);});
test('puzzle endings reject missing prerequisites before completion effects',()=>{for(const flag of ['spoke_selvane']){const f=finale('third_day');delete f.flags[flag];assert.equal(f.open(),false);assert.equal(f.root.xp,0);}for(const flag of ['clue_old_benediction_six_lines','clue_eron_inscription','officer_player','player_tried_saying']){const f=finale('charter');delete f.flags[flag];assert.equal(f.open(),false,flag);assert.equal(f.flags.chapter1_complete,undefined);}});
test('consequence endings recheck current eligibility even after options were built',()=>{const f=finale('uprising');f.at('tower_last_step');const stale=f.scene().options.find(o=>o.label.includes('city followed'));f.root.availableEndings=()=>({uprising:false});stale.action();assert.equal(f.flags.chapter1_complete,undefined);assert.equal(f.root.xp,0);});
test('epilogue claims survive state restoration and remote callbacks award nothing',()=>{const f=finale('third_day');f.open();const option=f.scene().options[1];f.engine.physicalReach=()=>false;option.action();assert.equal(f.root.xp,1200);f.engine.physicalReach=()=>true;option.action();option.action();assert.equal(f.root.xp,1350);const restored=finale('third_day');Object.assign(restored.flags,JSON.parse(JSON.stringify(f.flags)));restored.open();restored.scene().options[1].action();assert.equal(restored.root.xp,0);});
test('every ending presents its authored epilogue in 3D and returns to choices without duplicate rewards',()=>{for(const ending of ['sword','charter','third_day','uprising','restoration','devour']){const f=finale(ending);let shown;f.root.showScene=scene=>shown=scene;f.open();const option=f.scene().options.find(o=>o.label==='What happens now?');option.action();assert.match(shown.narration,/CHAPTER II/,ending);const xp=f.root.xp;shown.options[0].action();assert.ok(f.scene().options.length);option.action();assert.equal(f.root.xp,xp);assert.match(shown.narration,/already been recorded/);}});
test('epilogue return does not reopen remote ending choices',()=>{const f=finale('sword');let shown;f.root.showScene=scene=>shown=scene;f.open();f.scene().options[0].action();let opened=0;f.root.runScene=()=>opened++;f.engine.physicalContext=null;shown.options[0].action();assert.equal(opened,0);});
test('finished campaigns block stale combat and epilogues do not teleport',()=>{const f=finale('third_day');f.at('tower_last_step');const stale=f.scene().options.find(o=>o.type==='combat');f.open();stale.action();assert.equal(f.root.combats,0);f.root.goTo=()=>assert.fail('remote travel');f.scene().options.at(-1).action();assert.equal(f.engine.zone.id,'tower_antechamber');});
test('multiplayer guests cannot independently resolve or reward an ending',()=>{const f=finale('third_day');f.root.mp={sessionCode:'PARTY',isHost:false};assert.equal(f.open(),false);assert.equal(f.root.xp,0);f.root.mp.isHost=true;assert.equal(f.open(),true);});
test('completed Tower revisits route to the earned ending without an active quest or new combat',()=>{for(const ending of ['sword','charter','third_day','uprising','restoration','devour']){const f=finale(ending);f.open();f.root.gameState.activeQuests=[];f.root.sceneState.physicalSceneRequests={tower_last_step:'tower_charter_officer'};const restored=JSON.parse(JSON.stringify(f.root.sceneState));const next=Flow.nextScene('tower_last_step',restored,f.root.gameState);assert.equal(next,'tower_thirty_seventh_step');let destination;f.root.runScene=id=>destination=id;const xp=f.root.xp;assert.equal(f.root.SCENES[next](),null);assert.equal(destination,'tower_ending_'+ending);assert.equal(f.root.xp,xp);assert.equal(f.root.combats,0);}});
test('a completed flag without an earned ending cannot expose a Tower payoff',()=>{const state={flags:{chapter1_complete:true},physicalSceneRequests:{tower_last_step:'tower_charter_officer'}};assert.equal(Flow.nextScene('tower_last_step',state,{activeQuests:[]}),null);assert.equal(Flow.nextScene('tower_last_step',{flags:{}},{activeQuests:[]}),null);});
test('absent Cael cannot be selected as the charter officer',()=>{for(const fate of ['dead','arrested','fled']){const f=finale('charter');delete f.flags.officer_player;f.flags.officer_cael=true;f.root.npcAbsent=id=>id==='brother_cael';assert.equal(f.open(),false,fate);}});
test('direct puzzle scene access cannot manufacture name or charter knowledge',()=>{const f=fixture();f.flags.tower_door_answered=true;assert.equal(f.at('tower_last_step','tower_speak_his_name'),false);assert.equal(f.flags.spoke_selvane,undefined);assert.equal(f.at('tower_last_step','tower_charter_officer'),false);});
test('restoration eligibility requires Mourne present, not merely not dead',()=>{const root={runScene(){},sceneState:{flags:{}},gameState:{character:{holyPoints:50}},getRepScore:()=>50,getRepTier:()=>({id:'revered'})};root.window=root;vm.runInNewContext(fs.readFileSync(require.resolve('../site/consequences.js'),'utf8'),root);assert.equal(root.availableEndings().restoration,true);for(const fate of ['dead','arrested','fled']){root.sceneState.flags.npc_fate_sister_mourne=fate;assert.equal(root.availableEndings().restoration,false,fate);}});
