const test=require('node:test');const assert=require('node:assert/strict');
const fs=require('node:fs');const path=require('node:path');
test('Vaelthar production layout defines a complete multi-district capital',async()=>{const{VAELTHAR_DISTRICTS}=await import('../site/world3d/zones/vaelthar-layout.mjs');const ids=new Set(VAELTHAR_DISTRICTS.map(d=>d.id));for(const id of['main_square','watch_ward','signing_hall','temple_quarter','archive_lane','market','tarnished_cup','southward','crown_ward'])assert.ok(ids.has(id));assert.equal(ids.size,VAELTHAR_DISTRICTS.length);});
test('Vaelthar landmark anchors are unique and inside the city walls',async()=>{const{VAELTHAR_BOUNDS,VAELTHAR_LANDMARKS}=await import('../site/world3d/zones/vaelthar-layout.mjs');assert.equal(new Set(VAELTHAR_LANDMARKS.map(l=>l.id)).size,VAELTHAR_LANDMARKS.length);assert.ok(VAELTHAR_LANDMARKS.length>=9);for(const landmark of VAELTHAR_LANDMARKS){const[x,,z]=landmark.position;assert.ok(x>=VAELTHAR_BOUNDS.minX&&x<=VAELTHAR_BOUNDS.maxX);assert.ok(z>=VAELTHAR_BOUNDS.minZ&&z<=VAELTHAR_BOUNDS.maxZ);assert.ok(landmark.range>0);}});
test('physical Vaelthar landmarks connect to story, shop, and travel UI',async()=>{const{VAELTHAR_LANDMARKS}=await import('../site/world3d/zones/vaelthar-layout.mjs');const actions=new Map(VAELTHAR_LANDMARKS.map(l=>[l.id,l.action]));assert.equal(actions.get('signing_hall'),'scene:covenant_hall_scene');assert.equal(actions.get('temple_quarter'),'scene:temple_quarter_arrival');assert.equal(actions.get('tarnished_cup'),'scene:tarnished_cup_arrival');assert.equal(actions.get('ash_market'),'shop');assert.equal(actions.get('south_gate'),'map');});
test('the expanded city plan supplies curved streets, dense building plots, terraces, and market stalls',async()=>{const{VAELTHAR_CITY_SIZE,VAELTHAR_STREETS,VAELTHAR_BUILDING_PLOTS,VAELTHAR_TERRACES,VAELTHAR_MARKET_STALLS}=await import('../site/world3d/zones/vaelthar-city-plan.mjs');assert.ok(VAELTHAR_STREETS.length>=6);assert.ok(VAELTHAR_STREETS.every(street=>street.points.length>=4&&street.width>=3));assert.ok(VAELTHAR_BUILDING_PLOTS.length>=20);assert.equal(new Set(VAELTHAR_BUILDING_PLOTS.map(plot=>plot.id)).size,VAELTHAR_BUILDING_PLOTS.length);assert.ok(new Set(VAELTHAR_BUILDING_PLOTS.map(plot=>plot.district)).size>=7);assert.ok(VAELTHAR_BUILDING_PLOTS.every(plot=>Math.abs(plot.x)+plot.width/2<VAELTHAR_CITY_SIZE.wall&&Math.abs(plot.z)+plot.depth/2<VAELTHAR_CITY_SIZE.wall));assert.ok(VAELTHAR_TERRACES.some(terrace=>terrace.id==='citadel-rise'&&terrace.height>=4));assert.ok(VAELTHAR_MARKET_STALLS.length>=8);});
test('expanded Vaelthar NPCs stay within the playable city bounds',async()=>{const[{VAELTHAR_BOUNDS},{VAELTHAR_NPCS}]=await Promise.all([import('../site/world3d/zones/vaelthar-layout.mjs'),import('../site/world3d/vaelthar-npcs.mjs')]);for(const npc of VAELTHAR_NPCS){const[x,,z]=npc.position;assert.ok(x>=VAELTHAR_BOUNDS.minX&&x<=VAELTHAR_BOUNDS.maxX,npc.id);assert.ok(z>=VAELTHAR_BOUNDS.minZ&&z<=VAELTHAR_BOUNDS.maxZ,npc.id);}});
test('world labels respect scene depth and carry bounded-scale metadata',()=>{const source=fs.readFileSync(path.join(__dirname,'../site/world3d/zones/vaelthar-courtyard.js'),'utf8');assert.match(source,/depthTest:true/);assert.match(source,/depthWrite:false/);assert.match(source,/alphaTest:\.08/);assert.match(source,/worldLabelBase/);assert.doesNotMatch(source,/depthTest:false/);});
test('Vaelthar no longer builds districts from large circular ground plates',()=>{const source=fs.readFileSync(path.join(__dirname,'../site/world3d/zones/vaelthar-courtyard.js'),'utf8');assert.match(source,/pavingPatch/);assert.doesNotMatch(source,/district\.radius/);assert.doesNotMatch(source,/CircleGeometry\(10\.5/);});
